name: Deploy Go App to Server

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: go test -v ./...

      - name: Build Go binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o go-web-server .
          mkdir deployment
          mv go-web-server deployment/

      - name: Package artifact
        run: tar -czvf deployment.tar.gz deployment/

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "deployment.tar.gz"
          target: "/home/ubuntu/projects/"